#!/bin/bash
#Environment variables I must accept:
#$action
#$name

#Environment variables I need:
#$ServicePrincipalAppID=3ea0dd14-91eb-48f1-b116-bd90b3c1bf80
#$ServicePrincipalPassword=9b821ff6-c985-478f-aa9e-792b2a654b02
#$ServicePrincipalTenantID=b846a774-f39d-4a2d-9366-f3dda22c6bf0
#$SubscriptionID=3f61bfaa-f3af-4084-9c09-17e9b9d919d2
#$ResourceGroup=knab-poc
#$adminUsername
#$adminPasswordOrKey
deploymentName="${name}-deployment"

case $action in
    install)
    echo "Install action"
    set -x
	az login --service-principal --username $ServicePrincipalAppID --password $ServicePrincipalPassword --tenant $ServicePrincipalTenantID
	az account set --subscription $SubscriptionID

	az deployment group create \
		--resource-group $ResourceGroup \
		--template-file /knab/app/art/azuredeploy.json \
		--name $deploymentName \
		--parameters vmName=$name \
		adminUsername=$adminUsername \
		adminPasswordOrKey=$adminPasswordOrKey

	az deployment group show -n $deploymentName -g $ResourceGroup --query properties.outputs >> uncleanOutput.json
	python3 /knab/app/addValuesAndCleanJson.py
    ;;

    uninstall)
    echo "Uninstall action"
    set -x
	az login --service-principal --username $ServicePrincipalAppID --password $ServicePrincipalPassword --tenant $ServicePrincipalTenantID
	az account set --subscription $SubscriptionID
	az deployment group delete \
		--resource-group $ResourceGroup \
		--name $deploymentName 
    ;;

    upgrade)
    echo "Upgrade action"
    ;;

    *)
    echo "No action for $action"
    ;;
esac
echo "Action $action complete for $name"

	 